# -*- coding: utf-8 -*-
"""Swin-B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PumP8fV6XzJ7izPBpCYIj-oo_iJdwwE-
"""

# ​Cell 1: Setup & Data Mounting
import os
import json
import torch
import shutil
import zipfile
import pandas as pd
import torch.nn as nn
import torch.optim as optim
from PIL import Image
from tqdm import tqdm
from google.colab import drive
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms

# 1. Mount Google Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. Global Paths (Adjust if your folder names differ)
DRIVE_BASE = '/content/drive/MyDrive/FathomNet'
JSON_PATH = os.path.join(DRIVE_BASE, 'dataset_train.json')
TRAIN_ZIP = os.path.join(DRIVE_BASE, 'train_rois.zip')
TEST_ZIP = os.path.join(DRIVE_BASE, 'test_rois.zip')

# Saving under a new name to distinguish from your ResNet 'Build A'
MODEL_SAVE_PATH = os.path.join(DRIVE_BASE, 'swin_base_fathomnet.pth')
SUBMISSION_PATH = os.path.join(DRIVE_BASE, 'submission_swin.csv')

LOCAL_TRAIN_DIR = '/content/train_rois_local'
LOCAL_SORTED_DIR = '/content/train_data_sorted'
LOCAL_TEST_DIR = '/content/test_rois_local'

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

# Cell 2: Data Extraction & Taxonomic Sorting
def extract_data(zip_path, extract_to):
    if not os.path.exists(extract_to):
        os.makedirs(extract_to, exist_ok=True)
        print(f"📦 Extracting {os.path.basename(zip_path)}...")
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_to)
    else:
        print(f"⏩ {extract_to} already exists.")

extract_data(TRAIN_ZIP, LOCAL_TRAIN_DIR)
extract_data(TEST_ZIP, LOCAL_TEST_DIR)

# Map annotations to category IDs
with open(JSON_PATH, 'r') as f:
    train_metadata = json.load(f)
ann_to_cat = {str(ann['id']): str(ann['category_id']) for ann in train_metadata['annotations']}

if not os.path.exists(LOCAL_SORTED_DIR):
    os.makedirs(LOCAL_SORTED_DIR, exist_ok=True)
    print("📂 Sorting images into category folders...")
    for filename in tqdm(os.listdir(LOCAL_TRAIN_DIR)):
        if filename.endswith('.png'):
            try:
                ann_id = filename.split('_')[1].split('.')[0]
                cat_id = ann_to_cat.get(ann_id)
                if cat_id:
                    dest_folder = os.path.join(LOCAL_SORTED_DIR, cat_id)
                    os.makedirs(dest_folder, exist_ok=True)
                    shutil.move(os.path.join(LOCAL_TRAIN_DIR, filename), os.path.join(dest_folder, filename))
            except: continue

# Cell 3: Swin Transformer Training Phase
# 1. Transforms: Swin-B works best with these dimensions
train_transform = transforms.Compose([
    transforms.Resize((232, 232)),
    transforms.CenterCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(), # Helpful for underwater data
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_dataset = datasets.ImageFolder(root=LOCAL_SORTED_DIR, transform=train_transform)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2, pin_memory=True)
class_ids = train_dataset.classes

# 2. Model Initialization: Swin Base
model = models.swin_b(weights='IMAGENET1K_V1')
n_inputs = model.head.in_features
model.head = nn.Linear(n_inputs, len(class_ids)) # Replace head for FathomNet classes
model = model.to(DEVICE)

# 3. Optimization Setup
optimizer = optim.AdamW(model.parameters(), lr=5e-5, weight_decay=0.05)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)

# 4. Training Loop
num_epochs = 10
print(f"🔥 Training Swin Transformer...")
for epoch in range(num_epochs):
    model.train()
    for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    scheduler.step()

torch.save(model.state_dict(), MODEL_SAVE_PATH)
print(f"✅ Model saved to {MODEL_SAVE_PATH}")

# Cell 4: Inference & Submission Generation
# 1. Prediction Setup
id_to_concept = {cat['id']: cat['name'] for cat in train_metadata['categories']}
test_transform = transforms.Compose([
    transforms.Resize((232, 232)),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# 2. Predict
model.eval()
results = []
all_test_images = [os.path.join(LOCAL_TEST_DIR, f) for f in os.listdir(LOCAL_TEST_DIR) if f.endswith('.png')]

print(f"🧠 Generating predictions for {len(all_test_images)} images...")
with torch.no_grad():
    for img_path in tqdm(all_test_images):
        try:
            ann_id = os.path.basename(img_path).replace('.png', '')
            img = Image.open(img_path).convert('RGB')
            input_tensor = test_transform(img).unsqueeze(0).to(DEVICE)

            output = model(input_tensor)
            pred_idx = output.argmax(dim=1).item()

            cat_id_str = class_ids[pred_idx]
            concept_name = id_to_concept.get(int(cat_id_str), "Unknown")
            results.append({'annotation_id': int(ann_id), 'concept_name': concept_name})
        except: continue

# 3. Save CSV
df = pd.DataFrame(results)
df.to_csv(SUBMISSION_PATH, index=False)
print(f"🎉 Submission file ready at {SUBMISSION_PATH}")