# -*- coding: utf-8 -*-
"""FathomNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhX6It1wVqCleIGhNNsPorMcoZ0IAkxY
"""

import shutil
import os

# List of local folders to delete
folders_to_clear = ['/content/local_images', '/content/local_rois', '/content/temp_images', '/content/sample_data']

for folder in folders_to_clear:
    if os.path.exists(folder):
        shutil.rmtree(folder)
        print(f"Cleared: {folder}")

# Clear any abandoned zip files
!rm -rf /content/*.zip

print("✅ Local Colab storage is now clean.")

import os
from google.colab import drive

# 1. Mount Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. Setup Local Workspace (High Speed SSD)
!mkdir -p /content/raw_images
!mkdir -p /content/final_rois

# 3. Setup Drive Destination
DRIVE_OUTPUT = '/content/drive/MyDrive/FathomNet/train_rois_final'
os.makedirs(DRIVE_OUTPUT, exist_ok=True)

print("🚀 Environment ready. Ready for the Download + Auto-Crop script?")

import os
import json
import asyncio
import httpx
from PIL import Image
from tqdm.asyncio import tqdm_asyncio
from google.colab import drive

# --- 1. SETUP PATHS ---
DRIVE_BASE = '/content/drive/MyDrive/FathomNet'
JSON_PATH = os.path.join(DRIVE_BASE, 'dataset_train.json')
# We save CROPS to Drive, but download RAW to Local SSD
LOCAL_RAW_DIR = '/content/raw_tmp'
DRIVE_ROI_DIR = os.path.join(DRIVE_BASE, 'train_rois_final')

os.makedirs(LOCAL_RAW_DIR, exist_ok=True)
os.makedirs(DRIVE_ROI_DIR, exist_ok=True)

# --- 2. LOAD DATA ---
with open(JSON_PATH, 'r') as f:
    data = json.load(f)

image_map = {img['id']: img for img in data['images']}
annotations = data['annotations']

# --- 3. DOWNLOAD & CROP LOGIC ---
semaphore = asyncio.Semaphore(10) # Limit concurrent downloads to 10

async def process_entry(client, ann):
    async with semaphore:
        img_info = image_map.get(ann['image_id'])
        if not img_info: return

        url = img_info['coco_url']
        local_path = os.path.join(LOCAL_RAW_DIR, img_info['file_name'])
        roi_name = f"{ann['image_id']}_{ann['id']}.png"
        roi_path = os.path.join(DRIVE_ROI_DIR, roi_name)

        # Skip if ROI already exists on Drive
        if os.path.exists(roi_path): return

        try:
            # Download raw image if not already local
            if not os.path.exists(local_path):
                resp = await client.get(url, timeout=30.0)
                if resp.status_code == 200:
                    with open(local_path, "wb") as f:
                        f.write(resp.content)

            # Crop and save directly to Drive
            if os.path.exists(local_path):
                with Image.open(local_path) as img:
                    x, y, w, h = ann['bbox']
                    if w > 0 and h > 0:
                        crop = img.crop((int(x), int(y), int(x + w), int(y + h)))
                        crop.save(roi_path)

                # OPTIONAL: Delete local raw image to save space as we go
                # os.remove(local_path)
        except Exception:
            pass

async def main():
    limits = httpx.Limits(max_keepalive_connections=5, max_connections=10)
    async with httpx.AsyncClient(limits=limits) as client:
        tasks = [process_entry(client, ann) for ann in annotations]
        await tqdm_asyncio.gather(*tasks, desc="Downloading & Cropping")

# --- 4. EXECUTE ---
import nest_asyncio
nest_asyncio.apply()
asyncio.run(main())

print(f"\n✅ Done! Check your Drive: {DRIVE_ROI_DIR}")

from google.colab import drive
drive.mount('/content/drive')

import json

JSON_PATH = '/content/drive/MyDrive/FathomNet/dataset_train.json'

with open(JSON_PATH, 'r') as f:
    data = json.load(f)

# Create a dictionary: {category_id: "Scientific Name"}
# FathomNet uses 'categories' list for this
id_to_name = {str(cat['id']): cat['name'] for cat in data['categories']}

print(f"🧬 Found {len(id_to_name)} unique biological classes.")
print("Sample Mappings:")
for i, (cat_id, name) in enumerate(list(id_to_name.items())[:79]):
    print(f"  ID {cat_id} -> {name}")

# Search for Annotation ID 6
target_ann_id = 18317

found_cat = None
for ann in data['annotations']:
    if ann['id'] == target_ann_id:
        found_cat = str(ann['category_id'])
        break

if found_cat:
    print(f"✅ File {target_ann_id}.png belongs to Category ID: {found_cat}")
    print(f"🌿 Scientific Name: {id_to_name.get(found_cat, 'Unknown')}")
else:
    print("❌ Could not find that specific annotation ID in the JSON.")

import os
import zipfile
from tqdm import tqdm

# Paths
SOURCE_DIR = '/content/drive/MyDrive/FathomNet/train_rois_final'
ZIP_OUT = '/content/drive/MyDrive/FathomNet/train_rois.zip'

# Get list of all files to zip
files_to_zip = []
for root, dirs, files in os.walk(SOURCE_DIR):
    for file in files:
        files_to_zip.append(os.path.join(root, file))

print(f"📦 Total files to compress: {len(files_to_zip)}")

# Create the Zip with a progress bar
with zipfile.ZipFile(ZIP_OUT, 'w', zipfile.ZIP_STORED) as zipf:
    for file in tqdm(files_to_zip, desc="Zipping ROIs"):
        # arcname ensures the zip doesn't contain the full /content/drive... path
        arcname = os.path.relpath(file, SOURCE_DIR)
        zipf.write(file, arcname)

print(f"\n✅ Zip complete! Saved to: {ZIP_OUT}")
!du -sh {ZIP_OUT}