# -*- coding: utf-8 -*-
"""FathomNet2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hegc6fOe-nzfHCUUdGmaIKKj8QwEhvAr
"""

#zipping the 2 folder if not yet done

import os
import zipfile
from tqdm import tqdm
from google.colab import drive

# 1. Mount Google Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. CONFIGURATION
# The folder you want to zip (Change 'test_rois_final' to your target folder name)
SOURCE_DIR = '/content/drive/MyDrive/FathomNet/train_rois_final'

# Where to save the zip file and what to call it
ZIP_OUT_PATH = '/content/drive/MyDrive/FathomNet/train_rois.zip'

# 3. ZIP PROCESS
def zip_folder(source_dir, output_path):
    # Get a list of all files to calculate progress
    file_list = []
    for root, dirs, files in os.walk(source_dir):
        for file in files:
            file_list.append(os.path.join(root, file))

    print(f"📦 Total files to compress: {len(file_list)}")

    if len(file_list) == 0:
        print("❌ Error: The source folder is empty!")
        return

    with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for file in tqdm(file_list, desc="Zipping files"):
            # arcname prevents the zip from containing the full /content/drive... path
            arcname = os.path.relpath(file, source_dir)
            zipf.write(file, arcname)

# 4. EXECUTE
zip_folder(SOURCE_DIR, ZIP_OUT_PATH)

print(f"\n✅ Zip complete! File saved at: {ZIP_OUT_PATH}")
!du -sh {ZIP_OUT_PATH}

# ==========================================
# PHASE 1: ENVIRONMENT SETUP & DRIVE MOUNT
# ==========================================
import os
import json
import torch
import shutil
import zipfile
import pandas as pd
import torch.nn as nn
import torch.optim as optim
from PIL import Image
from tqdm import tqdm
from google.colab import drive
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms

# 1. Mount Google Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. Define Global Paths
DRIVE_BASE = '/content/drive/MyDrive/FathomNet'
JSON_PATH = os.path.join(DRIVE_BASE, 'dataset_train.json')
TRAIN_ZIP = os.path.join(DRIVE_BASE, 'train_rois.zip')
TEST_ZIP = os.path.join(DRIVE_BASE, 'test_rois.zip')
MODEL_SAVE_PATH = os.path.join(DRIVE_BASE, 'resnet50_build_a_plus.pth')
SUBMISSION_PATH = os.path.join(DRIVE_BASE, 'final_submission.csv')

# Local Colab SSD paths (for speed)
LOCAL_TRAIN_DIR = '/content/train_rois_local'
LOCAL_SORTED_DIR = '/content/train_data_sorted'
LOCAL_TEST_DIR = '/content/test_rois_local'

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==========================================
# PHASE 2: DATA EXTRACTION (TRAIN & TEST)
# ==========================================
def extract_data(zip_path, extract_to):
    if not os.path.exists(extract_to):
        os.makedirs(extract_to)
        print(f"📦 Extracting {os.path.basename(zip_path)}...")
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_to)
        print(f"✅ Extraction Complete: {len(os.listdir(extract_to))} files.")
    else:
        print(f"⏩ {extract_to} already exists. Skipping extraction.")

# Extract both datasets to the high-speed local SSD
extract_data(TRAIN_ZIP, LOCAL_TRAIN_DIR)
extract_data(TEST_ZIP, LOCAL_TEST_DIR)

# ==========================================
# PHASE 3: PRE-TRAINING DATA ORGANIZATION
# ==========================================
# We must sort images into folders based on category_id for ImageFolder to work
with open(JSON_PATH, 'r') as f:
    train_metadata = json.load(f)

# Map: Annotation ID -> Category ID
ann_to_cat = {str(ann['id']): str(ann['category_id']) for ann in train_metadata['annotations']}

print("📂 Sorting images into taxonomic folders for the model...")
os.makedirs(LOCAL_SORTED_DIR, exist_ok=True)

for filename in tqdm(os.listdir(LOCAL_TRAIN_DIR)):
    if filename.endswith('.png'):
        try:
            # Filename format: {img_id}_{ann_id}.png
            ann_id = filename.split('_')[1].split('.')[0]
            cat_id = ann_to_cat.get(ann_id)
            if cat_id:
                dest_folder = os.path.join(LOCAL_SORTED_DIR, cat_id)
                os.makedirs(dest_folder, exist_ok=True)
                shutil.move(os.path.join(LOCAL_TRAIN_DIR, filename),
                            os.path.join(dest_folder, filename))
        except: continue

# ==========================================
# PHASE 4: TRAINING (BUILD A+ LOGIC)
# ==========================================
# 1. Advanced Augmentation
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.ColorJitter(0.3, 0.3, 0.2, 0.05),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_dataset = datasets.ImageFolder(root=LOCAL_SORTED_DIR, transform=train_transform)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True, num_workers=2)
class_ids = train_dataset.classes # These are our folder names (Category IDs)

# 2. Setup Weighted Loss (Fixes class imbalance)
counts = [len(os.listdir(os.path.join(LOCAL_SORTED_DIR, c))) for c in class_ids]
weights = 1.0 / torch.tensor(counts, dtype=torch.float)
criterion = nn.CrossEntropyLoss(weight=weights.to(DEVICE), label_smoothing=0.1)

# 3. Initialize Model
model = models.resnet50(weights='IMAGENET1K_V1')
model.fc = nn.Linear(model.fc.in_features, len(class_ids))
model = model.to(DEVICE)

optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=0.01)
scheduler = optim.lr_scheduler.OneCycleLR(optimizer, max_lr=4e-4,
                                          steps_per_epoch=len(train_loader), epochs=15)

# 4. Training Loop
print(f"🔥 Starting Training on {DEVICE}...")
for epoch in range(15):
    model.train()
    for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/15"):
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        loss = criterion(model(images), labels)
        loss.backward()
        optimizer.step()
        scheduler.step()

torch.save(model.state_dict(), MODEL_SAVE_PATH)
print(f"💾 Model weights saved to {MODEL_SAVE_PATH}")

# ==========================================
# PHASE 5: INFERENCE & KAGGLE SUBMISSION
# ==========================================
# Map Category ID -> Scientific Name from JSON
id_to_concept = {cat['id']: cat['name'] for cat in train_metadata['categories']}

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

results = []
model.eval()

# Find all test images
all_test_images = []
for root, _, files in os.walk(LOCAL_TEST_DIR):
    for f in files:
        if f.endswith('.png'): all_test_images.append(os.path.join(root, f))

print(f"🧠 Predicting on {len(all_test_images)} test images...")
with torch.no_grad():
    for img_path in tqdm(all_test_images):
        try:
            # Extract Annotation ID from filename (e.g., '123.png' -> 123)
            ann_id = os.path.basename(img_path).replace('.png', '')

            img = Image.open(img_path).convert('RGB')
            input_tensor = test_transform(img).unsqueeze(0).to(DEVICE)

            output = model(input_tensor)
            _, pred_idx = torch.max(output, 1)

            # Map Index -> Cat ID -> Concept Name
            cat_id_str = class_ids[pred_idx.item()]
            concept_name = id_to_concept.get(int(cat_id_str), "Unknown")

            results.append({'annotation_id': int(ann_id), 'concept_name': concept_name})
        except: continue

# Create CSV
df = pd.DataFrame(results)
df.to_csv(SUBMISSION_PATH, index=False)
print(f"✅ Final Submission Saved! Total Rows: {len(df)}")