# -*- coding: utf-8 -*-
"""​ConvNeXt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHj4IxI8IdMeYJaR9_V1ctH6LdahCM-g
"""

# ​Cell 1: Environment & Paths
import os
import json
import torch
import shutil
import zipfile
import pandas as pd
import torch.nn as nn
import torch.optim as optim
from PIL import Image
from tqdm import tqdm
from google.colab import drive
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms

# 1. Mount Google Drive
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. Global Paths
DRIVE_BASE = '/content/drive/MyDrive/FathomNet'
JSON_PATH = os.path.join(DRIVE_BASE, 'dataset_train.json')
TRAIN_ZIP = os.path.join(DRIVE_BASE, 'train_rois.zip')
TEST_ZIP = os.path.join(DRIVE_BASE, 'test_rois.zip')

# Updated Model Name for Build B
MODEL_SAVE_PATH = os.path.join(DRIVE_BASE, 'convnext_base_build_b.pth')
SUBMISSION_PATH = os.path.join(DRIVE_BASE, 'submission_convnext.csv')

LOCAL_TRAIN_DIR = '/content/train_rois_local'
LOCAL_SORTED_DIR = '/content/train_data_sorted'
LOCAL_TEST_DIR = '/content/test_rois_local'

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

# Cell 2: Data Extraction & Sorting

def extract_data(zip_path, extract_to):
    if not os.path.exists(extract_to):
        os.makedirs(extract_to, exist_ok=True)
        print(f"📦 Extracting {os.path.basename(zip_path)}...")
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_to)
    else:
        print(f"⏩ {extract_to} exists. Skipping extraction.")

extract_data(TRAIN_ZIP, LOCAL_TRAIN_DIR)
extract_data(TEST_ZIP, LOCAL_TEST_DIR)

# Organize images by Category ID
with open(JSON_PATH, 'r') as f:
    train_metadata = json.load(f)

ann_to_cat = {str(ann['id']): str(ann['category_id']) for ann in train_metadata['annotations']}

if not os.path.exists(LOCAL_SORTED_DIR):
    os.makedirs(LOCAL_SORTED_DIR, exist_ok=True)
    print("📂 Sorting images...")
    for filename in tqdm(os.listdir(LOCAL_TRAIN_DIR)):
        if filename.endswith('.png'):
            try:
                ann_id = filename.split('_')[1].split('.')[0]
                cat_id = ann_to_cat.get(ann_id)
                if cat_id:
                    dest_folder = os.path.join(LOCAL_SORTED_DIR, cat_id)
                    os.makedirs(dest_folder, exist_ok=True)
                    shutil.move(os.path.join(LOCAL_TRAIN_DIR, filename), os.path.join(dest_folder, filename))
            except: continue

# Cell 3: Advanced Training (ConvNeXt-Base)
# 1. Stronger Augmentation for a deeper model
train_transform = transforms.Compose([
    transforms.Resize((232, 232)), # Slightly larger for ConvNeXt
    transforms.CenterCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_dataset = datasets.ImageFolder(root=LOCAL_SORTED_DIR, transform=train_transform)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2, pin_memory=True)
class_ids = train_dataset.classes

# 2. Weighted Loss
counts = [len(os.listdir(os.path.join(LOCAL_SORTED_DIR, c))) for c in class_ids]
weights = 1.0 / torch.tensor(counts, dtype=torch.float)
criterion = nn.CrossEntropyLoss(weight=weights.to(DEVICE), label_smoothing=0.1)

# 3. Model: ConvNeXt Base
# ConvNeXt is much more powerful than ResNet50
model = models.convnext_base(weights='IMAGENET1K_V1')
# Change the classifier head
n_inputs = model.classifier[2].in_features
model.classifier[2] = nn.Linear(n_inputs, len(class_ids))
model = model.to(DEVICE)

optimizer = optim.AdamW(model.parameters(), lr=5e-5, weight_decay=0.05)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)

# 4. Training Loop
num_epochs = 12
print(f"🔥 Training ConvNeXt-Base on {DEVICE}...")
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    scheduler.step()
    print(f"Epoch {epoch+1} Complete.")

torch.save(model.state_dict(), MODEL_SAVE_PATH)

# Cell 4: Optimized Inference
# 1. Setup
id_to_concept = {cat['id']: cat['name'] for cat in train_metadata['categories']}
test_transform = transforms.Compose([
    transforms.Resize((232, 232)),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# 2. Load Model
model.eval()
results = []
all_test_images = [os.path.join(LOCAL_TEST_DIR, f) for f in os.listdir(LOCAL_TEST_DIR) if f.endswith('.png')]

# 3. Predict
print(f"🧠 Predicting on {len(all_test_images)} images...")
with torch.no_grad():
    for img_path in tqdm(all_test_images):
        try:
            ann_id = os.path.basename(img_path).replace('.png', '')
            img = Image.open(img_path).convert('RGB')
            input_tensor = test_transform(img).unsqueeze(0).to(DEVICE)

            output = model(input_tensor)
            pred_idx = output.argmax(dim=1).item()

            cat_id_str = class_ids[pred_idx]
            concept_name = id_to_concept.get(int(cat_id_str), "Unknown")

            results.append({'annotation_id': int(ann_id), 'concept_name': concept_name})
        except: continue

# 4. Save
df = pd.DataFrame(results)
df.to_csv(SUBMISSION_PATH, index=False)
print(f"✅ Submission saved to {SUBMISSION_PATH}")